### ISSUE TITLE
Why use different hash functions? 

### ISSUE THREAD

**Issue by liu-jc** [stanford-futuredata/wmsketch#1]
Hi, I am interested in your work. But I am confused about the hash functions you used in your experiment. I have noticed you used PolynomialHash for countmin and paired_countmin, while TabulationHash for countsketch and logistic_sketch. 
Are they interchangeable? If not, what is the reason for this setting? Could you share the idea behind this?

**Comment by kaishengtai** [comment]
The short answer is that tabulation hashing can be used throughout in place of polynomial hashing, but when 2-independent hashing is required, the polynomial hash can be a bit faster to compute.

The count-min and count-sketch require 2-independent hashing, which can be implemented using a simple polynomial hash. Tabulation hashing is 3-independent, and so can be used in place of the polynomial hash.

The reason tabulation hashing is used in logistic_sketch is that the analysis calls for a higher degree of independence than just 2-independent hashing, and tabulation hashing is a simple hashing scheme that seems to work well in practice (see e.g. https://arxiv.org/abs/1011.5200). I didn't test to see if there was any measurable difference in performance in practice between the two hashing schemes.
